SansPapierMaintenanceBundle:
    resource: "@SansPapierMaintenanceBundle/Controller/"
    type:     annotation
    prefix:   /

SansPapierUserDataBundle:
    resource: "@SansPapierUserDataBundle/Controller/"
    type:     annotation
    prefix:   /profile

SansPapierShopBundle:
    resource: "@SansPapierShopBundle/Controller/"
    type:     annotation
    prefix:   /shop

SansPapierBooksMartBundle:
    resource: "@SansPapierBooksMartBundle/Controller/"
    type:     annotation
    prefix:   /books

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
# overrided
fos_user_register:
    resource: "@SansPapierUserDataBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@SansPapierUserDataBundle/Resources/config/routing/change_password.xml"
    prefix: /profile/change_password

    
