security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext
        

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        sp_userdatabundle:
            id: sans_papier_user_data.user_provider
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        fos_user:
            pattern: ^/
            form_login:
                provider: sp_userdatabundle
                csrf_provider: form.csrf_provider
                success_handler: sans_papier_user_data.authentication_handler
                failure_handler: sans_papier_user_data.authentication_handler
            logout:       true
            anonymous:    true 
            
       # login:
       #     pattern:  ^/demo/secured/login$
       #     security: false

       # secured_area:
       #     pattern:    ^/demo/secured/
       #     form_login:
       #         check_path: /demo/secured/login_check
       #         login_path: /demo/secured/login
       #     logout:
       #         path:   /demo/secured/logout
       #         target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
      #  - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/profile/preferences, role: ROLE_USER }
        - { path: ^/profile/selection/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/creditcard/, role: ROLE_USER }
        - { path: ^/shop/secure/request, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN        

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
